
name: Action Job

on:
  schedule:
    - cron: '0 * * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: run script
        run: |
          node ./run/index.js
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0
        with:
          publish-dir: './config'
          production-branch: master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: d3c379e7-7533-46cf-be3d-c50f46b92c35
